name: taxonomist
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  
  # DL
  - pytorch
  - torchvision
  - pytorch-cuda
  - lightning
  - optuna
  - wandb
  - transformers
  - huggingface_hub
  - datasets
  - torchmetrics

  # DS
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - pandas
  - pandas-profiling
  - opencv
  - pillow>=6.0.0
  - numba
  - dask
  - dask-ml
  - joblib

  # Plotting + viz
  - matplotlib
  - seaborn
  - bokeh
  - plotly
  - streamlit>=1.21
  - gradio

  # ipython + notebooks
  - ipython
  - notebook
  - jupyterlab
  - ipywidgets
  - ipykernel

  # Others
  - tqdm
  - pylint
  - pytest
  - ruff
  - openpyxl

  - pip
  - pip:
    - timm
    - black
    - albumentations
    - omegaconf
    - pygbif
    - bigtree
